<a href="https://colab.research.google.com/github/naveenkarri383/Generative_AI/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


# BOW (Bag of Words)

In [2]:
# Creating a example dataset
data=pd.DataFrame({"text":["people watch ineuron","ineuron watch ineuron","people write comment","ineuron write comment"]})

In [3]:
data

text
0   people watch ineuron
1  ineuron watch ineuron
2   people write comment
3  ineuron write comment

In [4]:
# Document matrix (Bag of words)
# Importing the class count vectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
BOW=CountVectorizer()  # creating a object

In [6]:
document_matrix=BOW.fit_transform(data["text"])

In [7]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [8]:
# Getting vocabulary
BOW.vocabulary_

# Arranging vocabularies based on the alphabets

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [9]:
# Getting Vectors
document_matrix[0].toarray()

array([[0, 1, 1, 1, 0]])

In [10]:
document_matrix[1].toarray()

array([[0, 2, 0, 1, 0]])

In [11]:
document_matrix[2].toarray()

array([[1, 0, 1, 0, 1]])

In [12]:
document_matrix[3].toarray()

array([[1, 1, 0, 0, 1]])

In [13]:
document_matrix[0:].toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

# N-GRAM

In [14]:
data

text
0   people watch ineuron
1  ineuron watch ineuron
2   people write comment
3  ineuron write comment

In [15]:
bi_gram=CountVectorizer(ngram_range=(2,2))

In [16]:
bi_gram_vocab=bi_gram.fit_transform(data["text"])

In [17]:
bi_gram_vocab.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [18]:
bi_gram.vocabulary_

{'people watch': 2,
 'watch ineuron': 4,
 'ineuron watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuron write': 1}

In [19]:
trigram=CountVectorizer(ngram_range=(3,3))

In [20]:
# Tri-Gram
tri_gram_vocab=trigram.fit_transform(data["text"])

In [21]:
trigram.vocabulary_

{'people watch ineuron': 2,
 'ineuron watch ineuron': 0,
 'people write comment': 3,
 'ineuron write comment': 1}

In [22]:
tri_gram_vocab.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [23]:
# Mixed Vocabulary
mix_vocab=CountVectorizer(ngram_range=(1,2))

In [24]:
mix_vocabulary=mix_vocab.fit_transform(data["text"])

In [25]:
mix_vocabulary.toarray()

array([[0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0],
       [0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1]])

In [26]:
mix_vocab.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3}

# TF-IDF (Term Frequency- Inverse Document Frequency)

In [27]:
# Importing class
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
tfidf=TfidfVectorizer()

In [29]:
#vectors
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [30]:
# Getting vocabulary
tfidf.get_feature_names_out()

# Arranged in a alphabetical order

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [31]:
tfidf.idf_  # IDF values

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])

# Assignment


# To the kaggle dataset

1. Need to perform one hot encoding on top of the text feature
2. Need to perform BOW from the text column
3. Need to perform N-grams also like 2-gram,3-gram and 4-gram
4. Need to perform the tf-IdentityFunction

Write 5 advantages and Disadvantages of  OHE vs BOW vs N-grams vs TF-IDF

